# Generated by Django 3.1 on 2020-08-18 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200818_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listedBy', to='auctions.user'),
            preserve_default=False,
        ),
    ]
