# Generated by Django 3.1 on 2020-08-18 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watched',
        ),
    ]
