# Generated by Django 3.1 on 2020-08-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200818_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
