# Generated by Django 3.1 on 2020-08-19 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200819_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='listingID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bided', to='auctions.listing'),
        ),
    ]
