# Generated by Django 3.1 on 2020-08-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20200819_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageLink',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
