# Generated by Django 3.1 on 2020-08-20 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20200819_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='listedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
