# Generated by Django 3.1 on 2020-08-20 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20200820_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currentbid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='currentbid', to='auctions.bids'),
        ),
    ]
