# Generated by Django 3.1 on 2020-08-20 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20200820_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='listingID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bided', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorize', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
